//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAddress
    {
        public int StudentAddressId { get; set; }
        public string StudentAddress1 { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual SchoolTable SchoolTable { get; set; }
    }
}
