//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstMVCApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyView12333
    {
        public int DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public int CourseId { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
